apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-controller-sshfs
  namespace: csi-sshfs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: csi-controller-sshfs
  template:
    metadata:
      labels:
        app: csi-controller-sshfs
    spec:
      priorityClassName: system-cluster-critical
      serviceAccountName: csi-controller-sshfs
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Equal
          value: "true"
          effect: NoSchedule
      containers:
        - name: csi-provisioner
          image: k8s.gcr.io/sig-storage/csi-provisioner:v2.1.0
          args:
            - -v=3
            - "--csi-address=$(ADDRESS)"
            - --leader-election
            - --leader-election-namespace=csi-sshfs
            - --extra-create-metadata
          env:
            - name: ADDRESS
              value: /csi/csi-provisioner.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: csi-attacher
          image: k8s.gcr.io/sig-storage/csi-attacher:v3.1.0
          args:
            - -v=3
            - "--csi-address=$(ADDRESS)"
            - --leader-election
            - --leader-election-namespace=csi-sshfs
          env:
            - name: ADDRESS
              value: /csi/csi-provisioner.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: sshfs
          image: patricol/csi-sshfs:latest
          imagePullPolicy: Always
          args:
            - run
            - -v=3
            - "--nodeid=$(NODE_ID)"
            - "--endpoint=$(CSI_ENDPOINT)"
            - --csi-driver-name=co.p4t.csi.sshfs
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix://csi/csi-provisioner.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
      volumes:
        - name: socket-dir
          emptyDir:
            medium: Memory
